SELECT TOP (100) * 
FROM ##TBL_CONDITIONS
WHERE UI_STD_DOG_CODE > 0 AND SECTOR IN ( 5000, 9400 ) AND ID = 6
ORDER BY SECTOR, UNIFIED, IS_SERVICE, EGFN_TYPE_CODE, DB_CLIENT_TYPE_DT300, CUSTOMER_CHARACTERISTIC_CODE
GO

SELECT [D].*, [C].*
FROM dbo.[AGR_CASH_PAYMENTS_DEALS] [D] WITH(NOLOCK)
INNER JOIN dbo.[AGR_CASH_PAYMENTS_CUSTOMERS] [C] WITH(NOLOCK)
	ON	[C].[CUSTOMER_ID] = [D].[CUSTOMER_ID]
WHERE [D].DEAL_STD_DOG_CODE = 39
	AND [C].[CLIENT_IDENTIFIER_TYPE] = 1
	AND [C].[CLIENT_TYPE_DT300_CODE] = 4
	AND [C].[CUSTOMER_CHARACTERISTIC] = 1
GO

SELECT * FROM SYS.tables
WHERE NAME LIKE 'AGR_CASH_PAYMENTS_DE%'
ORDER BY NAME
GO


-- [ID] - 6; STD 39
/******************************************************************************************************/
/******************************************************************************************************/
ALTER TABLE AGR_CASH_PAYMENTS_CUSTOMERS
	DROP COLUMN [HAS_MANY_CLIENT_CODES], [HAS_DUBL_CLIENT_IDS], [HAS_VALID_DOCUMENT]
GO
ALTER TABLE AGR_CASH_PAYMENTS_CUSTOMERS
	DROP COLUMN [HAS_LOAN], [IS_PROXY]
GO

/******************************************************************************************************/
/******************************************************************************************************/
ALTER TABLE AGR_CASH_PAYMENTS_CUSTOMERS
	ADD [HAS_MANY_CLIENT_CODES] BIT
	,	[HAS_DUBL_CLIENT_IDS] BIT
	,	[HAS_VALID_DOCUMENT] BIT
	,	[HAS_LOAN] BIT
	,	[IS_PROXY] BIT
GO

UPDATE [D]
SET [HAS_MANY_CLIENT_CODES] = 1
FROM AGR_CASH_PAYMENTS_CUSTOMERS [D]
INNER JOIN AGR_CASH_PAYMENTS_CUSTOMERS_WITH_MANY_CLIENT_CODES [S]
	ON [S].CUSTOMER_ID = [D].CUSTOMER_ID
GO

UPDATE [D]
SET [HAS_DUBL_CLIENT_IDS] = 1
FROM AGR_CASH_PAYMENTS_CUSTOMERS [D]
INNER JOIN AGR_CASH_PAYMENTS_CUSTOMERS_WITH_DUBL_EGFN [S]
	ON [S].CUSTOMER_ID = [D].CUSTOMER_ID
GO

UPDATE [D]
SET [HAS_LOAN] = 1
FROM AGR_CASH_PAYMENTS_CUSTOMERS [D]
INNER JOIN AGR_CASH_PAYMENTS_CUSTOMERS_WITH_LOANS [S]
	ON [S].CUSTOMER_ID = [D].CUSTOMER_ID
GO

UPDATE [D]
SET [IS_PROXY] = 1
FROM AGR_CASH_PAYMENTS_CUSTOMERS [D]
INNER JOIN AGR_CASH_PAYMENTS_CUSTOMERS_ARE_PROXIES [S]
	ON [S].CUSTOMER_ID = [D].CUSTOMER_ID
GO

UPDATE [D]
SET [HAS_VALID_DOCUMENT] = 1
FROM AGR_CASH_PAYMENTS_CUSTOMERS [D]
INNER JOIN AGR_CASH_PAYMENTS_CUSTOMERS_WITH_VALID_IDENTITY_DOCUMENTS [S]
	ON [S].CUSTOMER_ID = [D].CUSTOMER_ID
GO

/******************************************************************************************************/
/******************************************************************************************************/
ALTER TABLE AGR_CASH_PAYMENTS_DEALS
	DROP COLUMN HAS_TAX_UNCOLECTED
	,	HAS_OTHER_TAX_ACCOUNT
	,	HAS_LEGAL_REPRESENTATIVE
	,	HAS_PROXY
	,	HAS_DISTRAINT
	,	HAS_GS_INDIVIDUAL_PROGRAMME 
	,	HAS_WNOS_BEL 
	,	IS_DORMUNT_ACCOUNT 
	,	PROXY_COUNT
GO
 
/******************************************************************************************************/
/******************************************************************************************************/
ALTER TABLE AGR_CASH_PAYMENTS_DEALS
	ADD HAS_TAX_UNCOLECTED BIT 
	,	HAS_OTHER_TAX_ACCOUNT BIT
	,	HAS_LEGAL_REPRESENTATIVE BIT
	,	HAS_PROXY BIT
	,	HAS_DISTRAINT BIT
	,	HAS_GS_INDIVIDUAL_PROGRAMME BIT
	,	HAS_WNOS_BEL BIT
	,	IS_DORMUNT_ACCOUNT BIT
	,	PROXY_COUNT INT
GO

UPDATE [D]
SET HAS_TAX_UNCOLECTED = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_TAX_UNCOLECTED [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_OTHER_TAX_ACCOUNT = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_OTHER_TAX_ACCOUNT [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_LEGAL_REPRESENTATIVE = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_LEGAL_REPRESENTATIVE [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_PROXY = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_ACTIVE_PROXY_CUSTOMERS  [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_DISTRAINT = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_DISTRAINT  [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_GS_INDIVIDUAL_PROGRAMME = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_GS_INDIVIDUAL_PROGRAMME [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET HAS_WNOS_BEL = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_WNOS_BEL [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET IS_DORMUNT_ACCOUNT = 1
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN AGR_CASH_PAYMENTS_DEALS_WITH_DORMUNT_ACCOUNT [S]
	ON [S].DEAL_NUM = [D].DEAL_NUM
	AND [S].DEAL_TYPE = 1
GO

UPDATE [D]
SET PROXY_COUNT = [S].[CNT]
FROM AGR_CASH_PAYMENTS_DEALS [D]
INNER JOIN 
(
	SELECT [P].DEAL_NUM, COUNT(*) AS CNT
	FROM AGR_CASH_PAYMENTS_DEALS_ACTIVE_PROXY_CUSTOMERS [P]
	WHERE [P].DEAL_TYPE = 1
	GROUP BY [P].DEAL_NUM
) [S]
	ON	[S].DEAL_NUM = [D].DEAL_NUM
	AND [D].DEAL_TYPE = 1
GO


/******************************************************************************************************/
/******************************************************************************************************/
SELECT TOP (100) * 
FROM ##TBL_CONDITIONS
WHERE UI_STD_DOG_CODE > 0 AND SECTOR IN ( 5000, 9400 ) AND ID = 6
ORDER BY SECTOR, UNIFIED, IS_SERVICE, EGFN_TYPE_CODE, DB_CLIENT_TYPE_DT300, CUSTOMER_CHARACTERISTIC_CODE
GO

DECLARE @DateAcc DATE = '2022-04-05'
;
SELECT [X].DEAL_ROW_ID, [F].* 
FROM ##TBL_CONDITIONS [F] WITH(NOLOCK)
OUTER APPLY 
(
	SELECT TOP (1) [D].ROW_ID AS DEAL_ROW_ID
	FROM dbo.[AGR_CASH_PAYMENTS_DEALS] [D] WITH(NOLOCK)
	INNER JOIN dbo.[AGR_CASH_PAYMENTS_CUSTOMERS] [C] WITH(NOLOCK)
		ON	[C].[CUSTOMER_ID] = [D].[CUSTOMER_ID]

	WHERE [F].UI_STD_DOG_CODE = [D].DEAL_STD_DOG_CODE
		AND IsNull( [C].HAS_MANY_CLIENT_CODES, 0 ) = 0		/* [F].UNIFIED = 0 */
		AND IsNull( [C].HAS_DUBL_CLIENT_IDS, 0 ) = 0		/* [F].IS_SERVICE = 0 */
		AND [C].[CLIENT_IDENTIFIER_TYPE] = [F].[EGFN_TYPE_CODE]
		AND [C].[CLIENT_TYPE_DT300_CODE] = 	[F].[DB_CLIENT_TYPE_DT300]
--		AND [C].[CUSTOMER_CHARACTERISTIC] = [F].[CUSTOMER_CHARACTERISTIC_CODE]
		AND datediff(YY, str([C].[CLIENT_BIRTH_DATE],8,0), @DateAcc) BETWEEN [F].CUSTOMER_AGE_MIN AND [F].CUSTOMER_AGE_MAX 
		AND IsNull( [C].[HAS_LOAN], 0 ) = 0 /* ДА няма кредит */
		AND IsNull( [D].[HAS_LEGAL_REPRESENTATIVE], 0 ) = 1 /* UI_RAZPOREDITEL NOT NULL */
--		AND IsNull( [D].HAS_LEGAL_REPRESENTATIVE], 0 ) /* UI_RAZPOREDITEL NOT NULL */
		AND IsNull( [D].[HAS_OTHER_TAX_ACCOUNT], 0 ) = [F].[UI_OTHER_ACCOUNT_FOR_TAX] /* FOR UI_OTHER_ACCOUNT_FOR_TAX IN (0, 1) <> 2 */
--		AND IsNull( [D].[DEAL_NO_AUTO_PAY_TAX], 0 ) = [F].[UI_NOAUTOTAX] /* FOR [UI_NOAUTOTAX] <> -1 */
--		AND IsNull( [D].[DEAL_IS_DENY_MANUAL_TAX_ASSIGN], 0 ) = [F].[UI_DENY_MANUAL_TAX_ASSIGN] /* FOR [UI_DENY_MANUAL_TAX_ASSIGN] <> -1 */
--		AND IsNull( [D].[DEAL_CAPIT_ON_BASE_DATE_OPEN], 0 ) = [F].[UI_CAPIT_ON_BASE_DATE_OPEN] /* FOR [UI_CAPIT_ON_BASE_DATE_OPEN] <> -1 */
--		AND IsNull( [D].[DEAL_EXCLUDE_FROM_BANK_COLLECTIONS], 0 ) = [F].[UI_BANK_RECEIVABLES] /* FOR [UI_BANK_RECEIVABLES] <> -1 */
		AND [D].[DEAL_JOINT_ACCESS_TO_FUNDS_TYPE] = [F].[UI_JOINT_TYPE] /* FOR [D].[DEAL_IS_JOINT_DEAL] = 1 ! */
		AND [D].DEAL_BEG_DAY_BALANCE > 1000.0 -- [F].LIMIT_AVAILABILITY /* FOR [F].LIMIT_AVAILABILITY = 1 !!! */
		AND [D].[DEAL_IS_ACTIVE_DEAL] = 1 AND IsNull( [D].[IS_DORMUNT_ACCOUNT], 0 ) = 0 /* FOR [F].DEAL_STATUS = 1 */
		AND IsNull( [D].HAS_TAX_UNCOLECTED, 0 ) = 0 /* LIMIT_TAX_UNCOLLECTED = 0 */
--		AND IsNull( [D].HAS_DISTRAINT, 0 ) = [F].LIMIT_ZAPOR /* LIMIT_ZAPOR <> -1 !!! */
--		IS_UNIQUE_DEAL,	TAX_CODE,	PREF_CODE,	GS_PROGRAMME_CODE,	GS_CARD_PRODUCT, GS_PRODUCT_CODE
) [X]
WHERE [F].[SECTOR] IN ( 5000, 9400 )
--	AND [X].ROW_ID IS NULL
	AND [F].[ID] = 6
ORDER BY [F].SECTOR, [F].UNIFIED, [F].IS_SERVICE, [F].EGFN_TYPE_CODE
	, [F].DB_CLIENT_TYPE_DT300, [F].CUSTOMER_CHARACTERISTIC_CODE
GO
