SELECT * 
FROM SYS_LOG_PROC WITH(NOLOCK)
where id > 42
ORDER BY ID
GO

SELECT * FROM dbo.AGR_TA_EXISTING_ONLINE_DATA_DEALS
WHERE DEAL_IS_JOINT_DEAL = 1
go

SELECT	[REG].[DEAL_TYPE]
		,	[REG].[DEAL_NUM]

FROM dbo.AGR_TA_EXISTING_ONLINE_DATA_DEALS [REG] WITH(NOLOCK)
WHERE EXISTS (
SELECT	*
FROM BPB_VCSBank_Online.dbo.[TRAITEMS_DAY] [T] WITH(NOLOCK)
WHERE	[T].[DEAL_NUM]	= [REG].[DEAL_NUM]
	AND [T].[DEAL_TYPE] = 1
	AND	[T].[SUM_OPER] > 0
	AND [T].[REG_CODE_DEF] = 63 /* #define REG_VNOS_BEL_BIS6 63 */
) 

select top (1) * 
from BPB_VCSBank_Online.dbo.[DT015_CUSTOMERS]
where CUSTOMER_ID = 1257343
GO

select top (10) * 
from BPB_VCSBank_Online.dbo.[DT015_IDENTITY_DOCUMENTS]
where CUSTOMER_ID = 179016
GO
select top (1000) [N].CODE,  RTRIM([N].NAME) AS NAME 
-- , [E].*
from BPB_VCSBank_Online.dbo.[NOMS] [N]
INNER JOIN BPB_VCSBank_Online.dbo.[NM405] [E]
	ON [E].NOMID = [N].NOMID
	AND  [E].CODE =[N].CODE
WHERE DOCUMENT_USAGE_TYPE = 3
GO



SELECT * FROM  BPB_VCSBank_Online.dbo.[NOMS]
WHERE NOMID = 405
go

select 	[C].CUSTOMER_ID
	,	[D].ID
	,	[D].[EXPIRY_DATE]	AS [DOC_EXPIRY_DATE] 
	,	[D].INDEFINITELY	AS [DOC_INDEFINITELY]
from dbo.[AGR_TA_EXISTING_ONLINE_DATA_CUSTOMERS] [C]
INNER JOIN BPB_VCSBank_Online.dbo.[DT015_IDENTITY_DOCUMENTS] [D]
	ON	[C].CUSTOMER_ID = [D].CUSTOMER_ID
go

--DOCUMENT_STATUS: 1 - Активно; 2 - Неактивно;  3 - Оттеглено
-- VALIDITY_DATE : Валиден до
-- INDEFINITELY	 : Бесрочно

go
--After: SELECT * INTO dbo.[AGR_TA_EXISTING_ONLINE_DATA_DEALS_WITH_DORMUNT_ACCOUNT], Rows affected: 106077