WITH DEAL_WITH_WB AS 
(
	SELECT [DEAL_TYPE]
		,	[DEAL_NUM]
		,	CAST ( SYS_DATE AS DATE) AS SYSTEM_DATE
		,	COUNT(*) AS CNT
	FROM dbo.[TRAITEMS_DAY] WITH(NOLOCK)
	WHERE REG_CODE_DEF = 63 /* REG_VNOS_BEL_BIS6 63 */
		AND DEAL_TYPE = 1
		AND SUM_OPER > 1
		AND DT_CT = 2
	GROUP BY DEAL_TYPE, DEAL_NUM, CAST (SYS_DATE AS DATE)
)
SELECT	[T].BORD_NUM
	,	[T].[DEAL_TYPE]
	,	[T].[DEAL_NUM]
	,	[F].[SYSTEM_DATE]
	,	[T].[ACCOUNT]
	,	[F].[CNT]	AS [COUNT_WN_BEL]
FROM dbo.[TRAITEMS_DAY] [T] WITH(NOLOCK)
INNER JOIN DEAL_WITH_WB [F] WITH(NOLOCK)
	ON	[T].[DEAL_NUM] = [F].[DEAL_NUM]
	AND	[T].[DEAL_TYPE] = [F].[DEAL_TYPE]
	AND	CAST ([T].SYS_DATE  AS DATE) = [F].SYSTEM_DATE
WHERE [T].REG_CODE_DEF = 63 /* REG_VNOS_BEL_BIS6 63 */
		AND [T].DEAL_TYPE = 1
		AND [T].SUM_OPER > 1
		AND DT_CT = 2
ORDER BY [F].[CNT] DESC
GO
