/****** Object:  Index [IX_AGR_CASH_PAYMENTS_DEALS_DEAL_CURRENCY_CODE_DEAL_STD_DOG_CODE_CLIENT_SECTOR_DEAL_IS_JOINT_DEAL]    Script Date: 29.06.2022 ã. 15:07:22 ******/
DROP INDEX [IX_AGR_CASH_PAYMENTS_DEALS_DEAL_CURRENCY_CODE_DEAL_STD_DOG_CODE_CLIENT_SECTOR_DEAL_IS_JOINT_DEAL] ON [dbo].[AGR_CASH_PAYMENTS_DEALS]
GO

/****** Object:  Index [IX_AGR_CASH_PAYMENTS_DEALS_DEAL_CURRENCY_CODE_DEAL_STD_DOG_CODE_CLIENT_SECTOR_DEAL_IS_JOINT_DEAL]    Script Date: 29.06.2022 ã. 15:07:23 ******/
CREATE NONCLUSTERED INDEX [IX_AGR_CASH_PAYMENTS_DEALS_DEAL_CURRENCY_CODE_DEAL_STD_DOG_CODE_CLIENT_SECTOR_DEAL_IS_JOINT_DEAL] ON [dbo].[AGR_CASH_PAYMENTS_DEALS]
(
	[DEAL_CURRENCY_CODE] ASC,
	[DEAL_STD_DOG_CODE] ASC,
	[CLIENT_SECTOR] ASC,
	[DEAL_IS_JOINT_DEAL] ASC,
	[HAS_WNOS_BEL] ASC,
	[IS_DORMUNT_ACCOUNT] ASC
)
INCLUDE([DEAL_TYPE],[DEAL_NUM],[DEAL_ACCOUNT],[CUSTOMER_ID]) 
GO

CREATE NONCLUSTERED INDEX [IX_AGR_CASH_PAYMENTS_DEALS_ACTIVE_PROXY_CUSTOMERS_DEAL_TYPE_DEAL_NUM_CUSTOMER_ROLE_TYPE]
	ON [dbo].[AGR_CASH_PAYMENTS_DEALS_ACTIVE_PROXY_CUSTOMERS] ( [DEAL_TYPE], [DEAL_NUM], [CUSTOMER_ROLE_TYPE] )
INCLUDE ( [REPRESENTATIVE_CUSTOMER_ID] )
GO

create index IX_RAZPREG_TA_UI_DEAL_NUM_IS_BEN
on 	dbo.[RAZPREG_TA] (
	[UI_DEAL_NUM], [IS_BEN]
)
go

create index IX_DT015_CUSTOMERS_ACTIONS_TA_UI_CUSTOMER_ID
on dbo.[DT015_CUSTOMERS_ACTIONS_TA]
(
	[UI_CUSTOMER_ID], [TA_TYPE]
)
go
