SELECT DISTINCT TOP (500) 'ID_400052_CashPaymentCA_BETA_Company_Currency' AS [TEST_ID]
	,[DEAL].[DEAL_TYPE]
	,[DEAL].[DEAL_NUM]
	,[DEAL].CLIENT_CODE
	,[DEAL].CLIENT_SECTOR
	,[CUST].[CUSTOMER_ID]
	,[DEAL].DEAL_STD_DOG_CODE
	,[CUST].[CLIENT_TYPE_DT300_CODE]
--into CSTETMP_TEST_CASE_53_TEST_ID_400052_CashPaymentCA_BETA_Company_Currency
FROM dbo.[AGR_CASH_PAYMENTS_DEALS] [DEAL] WITH (NOLOCK)
INNER JOIN dbo.[AGR_CASH_PAYMENTS_CUSTOMERS] [CUST] WITH (NOLOCK) 
	ON	[CUST].[CUSTOMER_ID] = [DEAL].[CUSTOMER_ID]
	AND [DEAL].[CLIENT_SECTOR] = 6000
	AND [DEAL].[DEAL_CURRENCY_CODE] = 826
INNER JOIN dbo.[AGR_CASH_PAYMENTS_DEALS_ACTIVE_PROXY_CUSTOMERS] [PROXY_ID] WITH (NOLOCK) 
	ON	[PROXY_ID].[DEAL_NUM] = [DEAL].[DEAL_NUM]
	AND [PROXY_ID].[DEAL_TYPE] = 1
INNER JOIN dbo.[AGR_CASH_PAYMENTS_CUSTOMERS] [PROXY] WITH (NOLOCK)
	ON	[PROXY].[CUSTOMER_ID] = [PROXY_ID].[REPRESENTATIVE_CUSTOMER_ID]
WHERE [CUST].[CLIENT_TYPE_DT300_CODE] = 3
	AND [PROXY].[CLIENT_BIRTH_DATE] BETWEEN 18320513 AND 20040513
	AND [CUST].[HAS_MANY_CLIENT_CODES]		= 0
	AND [CUST].[HAS_DUBL_CLIENT_IDS] 		= 0
	AND [CUST].[CUSTOMER_CHARACTERISTIC]	= 0
	AND [PROXY].[HAS_VALID_DOCUMENT]		= 1
	AND [CUST].[HAS_LOAN]					= 0
	AND [DEAL].[PROXY_COUNT]				> 0
	AND [DEAL].[DEAL_STD_DOG_CODE]			= 1111
	AND [DEAL].[DEAL_IS_INDIVIDUAL_DEAL]	= 0
	AND [DEAL].[HAS_OTHER_TAX_ACCOUNT]		= 1
	AND [DEAL].[DEAL_IS_JOINT_DEAL] 		= 0
	AND [DEAL].[IS_DORMUNT_ACCOUNT] 		= 0
	AND [DEAL].[HAS_TAX_UNCOLECTED] 		= 0
	AND NOT EXISTS (
		SELECT *
		FROM dbo.[AGR_CASH_PAYMENTS_DEALS_WITH_OTHER_TAX_ACCOUNT] [TAX] WITH (NOLOCK)
		WHERE [TAX].[CORR_ACCOUNT] = [DEAL].[DEAL_ACCOUNT]
	)
	AND NOT EXISTS (
		SELECT *
		FROM dbo.[RAZPREG_TA] [TA] WITH (NOLOCK)
		WHERE [TA].[UI_DEAL_NUM] = [DEAL].[DEAL_NUM]
			AND [TA].[TA_TYPE] = 'CashPaymentCA_BETA_Company_Currency'
	)
go

SELECT * FROM CSTETMP_TEST_CASE_53_TEST_ID_400052_CashPaymentCA_BETA_Company_Currency 